FROM redis:3-alpine

ADD redis-server.nablet /redis-server.nablet
ADD ukvm-bin /ukvm-bin
ADD nabla_run /nabla_run

ADD redisaof.conf /data/conf/redisaof.conf
ADD redis.conf /data/conf/redis.conf

ENTRYPOINT ["/nabla_run", "--docker", "--ukvm", "/ukvm-bin", "--unikernel", "/redis-server.nablet"]
