seccomp: goapp.seccomp

goapp.a: $(wildcard *.go)
	go build -buildmode=c-archive -v -a -x 

goapp.pseudo: goapp.a
	RUMPRUN_STUBLINK=succeed x86_64-rumprun-netbsd-gcc -g -o goapp.pseudo _gorump_main.c goapp.a

goapp.seccomp: goapp.pseudo
	rumprun-bake solo5_ukvm_seccomp goapp.seccomp goapp.pseudo

%.bin: %.pseudo
	rumprun-bake hw_virtio $@ $<

clean:
	rm -f goapp.a goapp.h goapp.seccomp goapp.pseudo _gorump_main.c gomaincaller.go 
