# Copyright (c) 2018, IBM
# Copyright 2012-2015 Docker, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Based on the opencontainers/runc .travis.yml file.

dist: xenial
sudo: required
services:
  - docker
language: c
cache: ccache
compiler:
  - gcc
git:
    submodules: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

before_script:
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm libxen-dev libseccomp-dev bats genisoimage sudo iproute2 wget -y
  - sudo apt-get install --only-upgrade binutils gcc -y
  - export CC=gcc-6
  - export CXX=g++-6

env:
  - PLATFORM=solo5 MACHINE=x86_64

script:
  - export CC=gcc-6
  - export CXX=g++-6
  - (cd rumprun && NOGCCERROR=1 ./build-rr.sh -o obj -j16 -qq ${PLATFORM})
  - bash travis_wait.sh 60 make --quiet -C go-base gorump
  - bash travis_wait.sh 60 make --quiet -C nginx-base
  - bash travis_wait.sh 60 make --quiet -C node-base
  - make integration
#- make --quiet -C go-base build_docker
