FROM python:3.5.2-alpine

RUN apk update && apk add iproute2 git

ADD python3.nablet /python3.nablet
ADD ukvm-bin /ukvm-bin
ADD nabla_run /nabla_run

ENTRYPOINT ["/nabla_run", "--docker", "--ukvm", "/ukvm-bin", "--volume", \
	"/usr/local:/python", "--unikernel", "/python3.nablet"]
