FROM nginx:1.8-alpine

ADD nginx.nablet /nginx.nablet
ADD ukvm-bin /ukvm-bin
ADD nabla_run /nabla_run

COPY data /data

ENTRYPOINT ["/nabla_run", "--docker", "--ukvm", "/ukvm-bin", "--unikernel", "/nginx.nablet"]
